use_frameworks!

platform :ios, '9.0'

target 'ImageExtensionLibrary_Example' do
  pod 'ImageExtensionLibrary', :path => '../'

  target 'ImageExtensionLibrary_Tests' do
    inherit! :search_paths

    
  end
end
